### ISSUE TITLE
[EPIC] APEx openEO UDP benchmark & regression workflow

### ISSUE THREAD

**Issue by jdries** [ESA-APEx/apex_algorithms#1]
See: https://jdries-vito.quarto.pub/apex-design/algorithm_pipelines.html#integration-test

In APEx, a very important task is to check if algorithms still work, and to estimate their cost.
We expect a large number of algorithms, so need some tooling for that.
The main idea is to work UDP based, so that we can work with configuration in json rather than code.

The main configuration repo is this one (https://github.com/ESA-APEx/apex_algorithms), it contains:

- records describing the algorithm, pointing to the UDP's (some of them are also in this repo)
- json containing openEO requests that can be run, with job options
- backend info (endpoints, ...)

The runs generate:

- data files, to be compared with reference data stored in object storage. Comparison report should be html, to be put online?
- stac metadata, to be validated
- derived from link: to be compared with reference
- metrics/costs: to be stored in geoparquet on object storage

Prior work:

https://github.com/eu-cdse/openeo-benchmarks

**Comment by JeroenVerstraelen** [comment]
Ideas for possible improvements:

- [ ] Make sure that new github tickets also tag the contact person of the scenario
- [x] Should be easy to know if you just have to update the reference data
- [ ] Private: doesn't have exactly the same config as the public one
- [ ] Private: also auto issue creation + auto tagging
  * Jira support board? Because issue, report, or log might contain sensitive information
  * It would be great if we can just use github for this
- [x] Private: run against terrascope-dev
- [ ] Private: add tool to easily run against production to verify if staging/dev had a regression
  * Perhaps automatically run against production if test fails
- [ ] Raster comparison should be easier
- [ ] Is the report easily available for very quick checks?

**Comment by jdries** [comment]
@JeroenVerstraelen  I now logged an important sub-issue that apparently got lost somewhere: https://github.com/ESA-APEx/apex_algorithms/issues/270

**Comment by JeroenVerstraelen** [comment]
@jdries @HansVRP The acceptance criteria and sub-issues (stories) are not clear for this Epic. 

According to the planning:
* By APEX MVP (oct 2024) a basic setup should be there (V)
* Try to have a very basic thing in june 2024 (V)
* Get feedback, and elaborate over summer

What is requested of the Python team in order for this to be complete?

**Comment by HansVRP** [comment]
@VictorVerhaert will pull this exercise from DE side. 

The most important thing is that we expose through job metadata the most important metrics which can be used to track regression. On DE side of things we wish to pull this information out of the job logs and provide a visualisation of the performance change and/or an error. 

One thing which currently also came up; both on the jenkins as the github side of things we make use of the same reference data. When in 'dev' we notice we need to update the data and/or metadata, github will run agains prod with the new references and fail. 

Improving this set-up will also be needed to not create too many false-positives

**Comment by JeroenVerstraelen** [comment]
Thanks @HansVRP if a list of user stories can be provided then we will work on further refinement and planning for a subset to be completed by the end of Q2.

**Comment by JeroenVerstraelen** [comment]
Current list of features we would add for Q2/Q3. @VictorVerhaert feel free to provide feedback here if you'd like different features.
- [ ] Change private benchmarks: send mail to owner and topic in openeo-devs when a benchmark fails
- [ ] openeo-admin status dashboard for private benchmarks with information from the latest failing tests 
  * What are the latest failing tests
  * Who is the owner (contact information), test_error_message, comments, status
  * How long has the test been failing
  * Freely editable, similar to the excel sheets we used up to now
- [ ] openeo-admin benchmark details
  * compare actual, reference results
  * See results from dev, staging, prod
  * See logs difference between actual, reference
  * See logs differences between dev, staging, prod
  * peak JVM memory, other mimir/prometheus data
    * is it more expensive, is there a regression? 
  * jobregistry information: usage, duration
    * is it more expensive, is there a regression? 
  * Open in qgis (the leaflet visualization can be off, so best to remove)

**Comment by JeroenVerstraelen** [comment]
### Final list of tasks to be implemented for Q2/Q3

**DE team**
* performance regression testing (PR @HansVRP) #490  

**Python team**
* openeo-admin features + private benchmark alerts listed above
* Bug: in private benchmarks the terrascope tests can override CDSE tests
* separate reference data from dev and prod tests
  * Currently when it fails in dev then the reference data is updated, which causes it to fail in prod and vice versa.
  * These should be separated: openeo-apex-tests [dev] should have different reference data compared to ESA-APEx/apex_algorithms [prod]
  * Optional: dev changes should be auto-committed to prod whenever we deploy a new version  
* timeseries of performance over time 
  * [Include extra metrics in usage #970](https://github.com/eu-cdse/openeo-cdse-infra/issues/970) [Scala team] 
  * extra dashboard in openeo-admin
