### ISSUE TITLE
[EPIC] Populate algorithm catalog

### ISSUE THREAD

**Issue by jdries** [ESA-APEx/apex_algorithms#28]
EPIC to add a first set of (existing) UDP's to the algorithm catalog.

Guidelines for creating examples will soon appear here:

https://esa-apex.github.io/apex_documentation/eo_service_usage.html

We currently consider these lists:

VITO:
- [ ] BAP composite
- [ ] FuseTS/AI4Food UDP's (cropsar, mogpr)
- [ ] BioPar (VITO version)
- [ ] WorldCereal first version
- [ ] Max-NDVI composite
- [ ] [Sentinel-1 stats](https://github.com/Open-EO/openeo-community-examples/blob/main/python/Sentinel1_Stats/Sentinel1_Stats.ipynb)

Non-VITO:
- [ ] ESA WorldWater (DHI)
- [ ] GTIF Wind Turbine (DHI)
- [ ] PV farm detection (EURAC)
- [ ] Sen2Like (EODC)
- [ ] Biopar (EODC)

**Comment by jdries** [comment]
@Patrick1G  This is the overview issue, allowing to easily maintain a list of UDP's we would aim for in the MVP.
@JeroenVerstraelen  @HansVRP  We'll want to consider this for planning.

**Comment by Patrick1G** [comment]
@jdries that looks like  good starting point. 
We could consider a couple of other examples from the community examples repo (also to have a good balance with non VITO workflows)... The [parcel delineation algo](https://github.com/Open-EO/openeo-community-examples/tree/d5d54bdc86cd58e5194268df312d186dd26a0755/python/ParcelDelineation) would certainly also be interesting for users, yet developed by VITO...

**Comment by Patrick1G** [comment]
oh and PS; what's the point of having an EODC and VITO version of biopar?

**Comment by HansVRP** [comment]
@jdries what requirements do we have on the input parameters for the to be included openEO processes? 

bbox and temporal range?

**Comment by jdries** [comment]
@HansVRP  that's usually the minimum, but it actually depends on the UDP.
Now this is considered public API, so once a parameter is introduced, changing it is not backwards compatible.
So the general recommendation is to start out with a minimal set.

**Comment by HansVRP** [comment]
Good to know there are no restrictions. 
Some of the listed probably also have some parameters related to the used ML network ect.

**Comment by Patrick1G** [comment]
@jdries @JanssenBrm  to be true to the APEx vision, we would (or will eventually) also expose other algorithms hosted o other platforms. Below is a listing of EOXhub algorithms from the NOR.. Several of those use an Application Package implementation.. 
I wonder if we could aggregate a few of these early on...

![image](https://github.com/user-attachments/assets/cd103904-6fa7-4db9-b00b-e6a6766b6ac9)

**Comment by jdries** [comment]
@Patrick1G  this indeed looks like a nice collection to integrate, especially also very mature with respect to having pricing and so on.
The only prerequisite from our side is that we need the OGC Processes API to invoke it (or openEO, but that doesn't seem to be applicable here). I checked the docs, which mention an api on this page:
https://eurodatacube.com/documentation/generate_data_on_demand
but it doesn't look like OGC Processes at first sight. Could you check with EDC if they can give us such an endpoint, or should we reach out?

**Comment by Patrick1G** [comment]
> @Patrick1G this indeed looks like a nice collection to integrate, especially also very mature with respect to having pricing and so on. The only prerequisite from our side is that we need the OGC Processes API to invoke it (or openEO, but that doesn't seem to be applicable here). I checked the docs, which mention an api on this page: https://eurodatacube.com/documentation/generate_data_on_demand but it doesn't look like OGC Processes at first sight. Could you check with EDC if they can give us such an endpoint, or should we reach out?

I asked EOX to look into this, but have not heard anything back (purposefully hesitant?) 

I have asked PLES team to look into this in the meantime..

**Comment by p3dr0** [comment]
added two examples on this pull request 
https://github.com/ESA-APEx/apex_algorithms/pull/39
I'll add more after checking with @jdries the are ok

**Comment by Patrick1G** [comment]
@p3dr0 @JanssenBrm @psacra 
For APEx to integrate the Elip and EDC/EOXhub services/algos above, APEx needs to have a valid subscription to all the relevant platforms, to be obtained from the NOR (now?). This should also cover testing requirements..

**Comment by p3dr0** [comment]
We'd need to size it according to the planned test scenarios (daily, hour) and the duration (next 6 months? )
I'll update the list of services on the PR, add the metadata element missing and draft a NoR request for it

**Comment by jdries** [comment]
@p3dr0  see my other comment for the sizing: please adjust the frequency depending on the scenario cost. I would start from weekly frequency for cheap scenarios. Higher frequency seems like overkill, and because we are likely to run multiple scenarios against the same platform, we will still have a pretty high per platform frequency that allows us to detect general issues in a timely manner.

**Comment by Patrick1G** [comment]
@jdries @JanssenBrm 
could we look into completing the initial list above, especially the non VITO algorithm services? 

We should then also set up a new list of algorithms for integration!

**Comment by jdries** [comment]
I reached out to EODC to get their processes onboarded.
DHI windturbine UDP is reported as ready, so I'm supporting them on creating the catalog record.
After that I plan to follow up with them on the WorldWater UDP.
